### PR TITLE
Chore: Consistent Whitespace

### PR DESCRIPTION
**Pull request by Zandario**
Welcome to pointless chores with @Zandario, today some funny spaces and tabs annoyed me

## About
I noticed a lot of trailing white-space and a couple tabbed lines, so I took some time to make it consistent, also removed a weird double space inside of every units' definitions. Of course the templates were adjusted to match.

### CODE REVIEW

**Comment by ProbablePrime** [comment]
Can you also add an .editorconfig ? FrooxEngine's editor config can be found here: https://i.probableprime.co.uk/231104-MdffN7WOjRqQld8Iiac4.txt

Feel free to do this to all of our dependencies if you're that way inclined, It will help out but it is a large ask :)

**Comment by Zandario** [comment]
> Can you also add an .editorconfig ? FrooxEngine's editor config can be found here: [i.probableprime.co.uk/231104-MdffN7WOjRqQld8Iiac4.txt](https://i.probableprime.co.uk/231104-MdffN7WOjRqQld8Iiac4.txt)
> 
> Feel free to do this to all of our dependencies if you're that way inclined, It will help out but it is a large ask :)

OH GLADLY

**Comment by Zandario** [comment]
@ProbablePrime Requested Review 🏓

**Review by ProbablePrime — APPROVED** [review]

**Comment by ProbablePrime** [comment]
Thank you!

**Pull request merged**
